webServer:
  serverAddress: "http://*:27015/"

exampleFiles: true # Writes some example files

# You can get the files with this urls
# index: http://localhost:27015/
# 404: http://localhost:27015/404
# Military Top Image: http://localhost:27015/1011